---
title: Exploration of the Exponential Distribution and the Central Limit Theorem on
  Mean and Variance
author: "Bill Martersteck"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  html_document:
    toc: yes
  pdf_document:
    toc: yes
---

```{r setup, include=FALSE}
require(knitr)
require(markdown)

knitr::opts_chunk$set(echo = TRUE)
```

## Overview:
In a few (2-3) sentences explain what is going to be reported on.

## Simulations:
Include English explanations of the simulations you ran, with the accompanying R code. Your explanations should make clear what the R code accomplishes.

## Sample Mean versus Theoretical Mean:
Include figures with titles. In the figures, highlight the means you are comparing. Include text that explains the figures and what is shown on them, and provides appropriate numbers.

## Sample Variance versus Theoretical Variance:
Include figures (output from R) with titles. Highlight the variances you are comparing. Include text that explains your understanding of the differences of the variances.

## Distribution:
Via figures and text, explain how one can tell the distribution is approximately normal.
